name: server_blu_remote
description: A Dart server that receives Bluetooth signals from a Flutter remote mouse app
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.0
  shelf_web_socket: ^1.0.0
  win32: ^5.0.0
  ffi: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
